1st approach restaurant
gapinal/events pull request #3
Opened 2018-07-27 02:56 UTC by gapinal

2018-08-02 00:19 UTC, nmicht requested changes
I left a lot of comment on your code.
Please review, fix and update

2018-08-02 00:19 UTC, nmicht commented on css/styles.css
> +.segment-one button {
Is better to assign class names related to the content instead the position or the styling

2018-08-02 00:19 UTC, nmicht commented on css/styles.css
> +    background-color: #e51a94;
Use the colors as variables

2018-08-02 00:19 UTC, nmicht commented on index.html
> +    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
You should use font-awesome as a dependency, from node_modules

2018-08-02 00:19 UTC, nmicht commented on index.html
> +            <button type="button" name="button">ENVIAR</button>
Remove the `name` attribute from the button

2018-08-02 00:19 UTC, nmicht commented on index.html
> +            <br><br>El mejor Restaurante dedicado al espacio lúdico de Juegos de Mesa. Contamos con los mejores juegos de mesa, tienda. expertos en diversión y un menú deliciosamente divertido.
Do not use `br`. In this case is better to have two paragraphs and margin between them.

2018-08-02 00:19 UTC, nmicht commented on index.html
> +        <div><img src="images/people.png" alt=""></div>
Always always have the `alt` attribute with information related to the image

2018-08-02 00:19 UTC, nmicht commented on index.html
> +        <div class="content">
For the contact information will be great to use `address` tag
See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address

2018-08-02 00:19 UTC, nmicht commented on index.html
> +                <span>3629·4947</span>
You can use the telephone with a link to make a call directly
See https://css-tricks.com/the-current-state-of-telephone-links/

2018-08-02 00:19 UTC, nmicht commented on package.json
> +  "author": "Georgia Andrea Pinal",
Include your email also
```
"author": {
    "name": "asdfasdf",
    "email": "asdfasdfasd"
}
```

2018-08-02 00:19 UTC, nmicht commented on package.json
> +    "url": "https://github.com/gapinal/proyecto_final/issues"
Update the url with your github url

2018-08-10 00:25 UTC, gapinal commented
media query

2018-08-10 00:25 UTC, gapinal commented
media query done last pull request

2018-08-10 00:27 UTC, closed without merging